### ISSUE TITLE
Configure HTTPS Ingress with cert-manager via own ClusterIssuer

### ISSUE THREAD

**Issue by manicole** [magda-io/magda-config#16]
Hi all, I'm trying to configure an Ingress with cert-manager for HTTPS access.

In values.yaml file, I changed the folllowing : 
```yaml
tags:
  ingress: true
...
magda:
  magda-core:
    ingress:
      hostname: magda.<domain-name>
      # ipName:
      # ingressClass: gce
      enableTls: true
      tlsSecretName: "magda-cert-tls"
      domains:
        - magda.<domain-name>
```

I'd like to be able to add an annotation in the Ingress to call for my own cert-manager ClusterIssuer.
Is it possible (can't find a way) ? Will it be in a near future ?
Thanks
